const assert = require("node:assert/strict")
const fs = require("node:fs")

const read = path => fs.readFileSync(path, "utf8")
const ci = read(".github/workflows/ci.yml")
const release = read(".github/workflows/release.yml")
const dependabot = read(".github/dependabot.yml")
const packageMetadata = JSON.parse(read("package.json"))
const compatibility = fs.existsSync(".github/workflows/compatibility.yml")
  ? read(".github/workflows/compatibility.yml")
  : ""
const labeler = read(".github/labeler.yml")
const labelsWorkflow = read(".github/workflows/labels.yml")
const issueForms = fs.readdirSync(".github/ISSUE_TEMPLATE")
  .filter(name => name.endsWith(".yml") && name !== "config.yml")
  .map(name => read(`.github/ISSUE_TEMPLATE/${name}`))
const capture = fs.existsSync("scripts/capture-screenshots")
  ? read("scripts/capture-screenshots")
  : ""
const runner = read("tests/run_all.sh")
const preCommit = read("scripts/pre-commit")

assert.match(ci, /bolens\/.github\/.github\/workflows\/reusable-actionlint\.yml@3f2e5f3e61c419f3678ea8f472d24562254624c6/)
assert.match(ci, /security-audit: true/)
assert.match(ci, /dorny\/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d/)
assert.equal((ci.match(/'\.github\/labeler\.yml'/g) || []).length, 2)
assert.match(ci, /filters:\s*\|[\s\S]*?plugin:[\s\S]*?'\.github\/labeler\.yml'[\s\S]*?repository:/)
assert.match(ci, /repository:[\s\S]*?'\.github\/labeler\.yml'/)
assert.match(ci, /plugin:\s*\$\{\{\s*github\.event_name\s*!=\s*'pull_request'\s*\|\|\s*steps\.filter\.outputs\.plugin\s*==\s*'true'\s*\}\}/)
assert.match(ci, /repository:\s*\$\{\{\s*github\.event_name\s*!=\s*'pull_request'\s*\|\|\s*steps\.filter\.outputs\.repository\s*==\s*'true'\s*\}\}/)
assert.equal((ci.match(/CHANGES_RESULT:\s*\$\{\{ needs\.changes\.result \}\}/g) || []).length, 2)
assert.equal((ci.match(/\[\[ "\$CHANGES_RESULT" == success \]\]/g) || []).length, 2)
assert.equal((ci.match(/\[\[ "\$SELECTED" == true \|\| "\$SELECTED" == false \]\]/g) || []).length, 2)
assert.match(ci, /plugin-result:[\s\S]*name: Plugin[\s\S]*if: always\(\)/)
assert.match(ci, /repository-result:[\s\S]*name: Repository[\s\S]*if: always\(\)/)
assert.match(ci, /actions\/setup-node@820762786026740c76f36085b0efc47a31fe5020/)
assert.match(ci, /shellcheck/)
assert.match(ci, /lycheeverse\/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8/)
assert.match(ci, /--exclude-path '[^']*node_modules/)
assert.match(ci, /accessibility\.score\s*===\s*1|score\s*===\s*1/)
assert.match(ci, /13f18b2cb7286fb54f87daf571a031aa6af3d8f0/)
assert.match(ci, /concurrency:[\s\S]*cancel-in-progress:\s*true/)
assert.doesNotMatch(ci, /runs-on:\s*ubuntu-latest/)
assert.match(ci, /PRIVATE KEY\|gh\[pousr\]_/)

assert.match(compatibility, /schedule:/)
assert.match(labelsWorkflow, /pull_request_target:/)
assert.match(labelsWorkflow, /permissions:\s*\{\}/)
assert.match(labelsWorkflow, /pull-requests:\s*write/)
assert.doesNotMatch(labelsWorkflow, /issues:\s*write/)
assert.doesNotMatch(labelsWorkflow, /actions\/checkout@/)
assert.match(labelsWorkflow, /actions\/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13/)
assert.match(labelsWorkflow, /sync-labels:\s*true/)
for (const label of ["bug", "enhancement", "documentation", "dependencies", "docker", "github-actions", "ci", "tests", "qml", "javascript", "shell", "site", "metadata", "release"])
  assert.match(labeler, new RegExp(`^${label}:`, "m"))
assert.ok(issueForms.length >= 2)
for (const form of issueForms) assert.match(form, /^labels: .*needs-triage/m)
assert.equal((ci.match(/ghcr\.io\/bolens\/omarchy-plugin-ci@sha256:293b0457198085de5df26519dd4aa336202495c080d253b71ac30e7d8e8d3851/g) || []).length, 1)
assert.equal((compatibility.match(/ghcr\.io\/bolens\/omarchy-plugin-ci@sha256:293b0457198085de5df26519dd4aa336202495c080d253b71ac30e7d8e8d3851/g) || []).length, 1)
assert.doesNotMatch(ci, /\bpacman\s+-Syu\b/)
assert.doesNotMatch(compatibility, /\bpacman\s+-Syu\b/)
assert.match(compatibility, /13f18b2cb7286fb54f87daf571a031aa6af3d8f0/)
assert.match(compatibility, /omarchy-ref:\s*quattro/)
assert.match(compatibility, /workflow_dispatch:/)
assert.match(compatibility, /npm ci --ignore-scripts/)
assert.match(compatibility, /\$GITHUB_WORKSPACE:\/source:ro/,
  "compatibility checks must not write into the checkout")
assert.match(compatibility, /--tmpfs \/workspace:/,
  "compatibility checks need an isolated writable workspace")
assert.match(compatibility, /cp -a \/source\/\. \/workspace/,
  "compatibility checks must copy the read-only checkout into the isolated workspace")
assert.match(runner, /git archive HEAD \| tar -x -C "\$validation_dir"/)
assert.match(runner, /omarchy plugin validate "\$validation_dir"/)
assert.match(preCommit, /archive "\$\(git -C "\$root" write-tree\)"/)
assert.match(preCommit, /PRIVACY_RUNTIME_TESTS=never/)
assert.ok(fs.statSync(".githooks/pre-commit").mode & 0o100)

assert.match(release, /actions\/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8/)
assert.match(release, /id-token:\s*write/)
assert.match(release, /attestations:\s*write/)
assert.match(release, /validate:[\s\S]*?checks:\s*write/)
const releaseValidateJob = release.match(/^  validate:\n[\s\S]*?(?=^  \S)/m)
assert.ok(releaseValidateJob, "release workflow must define the reusable validate job")
assert.match(releaseValidateJob[0], /^    permissions:\n(?:(?:      .+)\n)*?      pull-requests:\s*read$/m)
assert.match(release, /concurrency:[\s\S]*cancel-in-progress:\s*false/)
assert.doesNotMatch(release, /runs-on:\s*ubuntu-latest/)
assert.match(release, /persist-credentials:\s*false/)

assert.equal(packageMetadata.engines.node, ">=24.19.0")
assert.equal(packageMetadata.packageManager, "npm@11.19.0")
assert.equal((dependabot.match(/interval:\s*weekly/g) || []).length, 2)

assert.ok(fs.statSync("scripts/capture-screenshots").mode & 0o100)
assert.match(capture, /trap .*?(cleanup|restore)/)
assert.match(capture, /restore/)
assert.match(capture, /--verify/)
assert.match(capture, /--report/)
assert.doesNotMatch(capture, /quickshell\s+(kill|--kill)|qs\s+kill/)

console.log("Fleet hardening contracts passed")
